version: "3.8"
services:
  server:
    container_name: csxp_server
    image: csxpi_server
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.server
    ports:
      - 8881:80
    environment:
      DISABLE_UPLOAD: 'false'
      SEARCH_SOURCE: 'mongo'
      ELASTIC_PASSWORD: ${ELASTIC_PASS}
      MONGO_USERNAME: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASS}
    depends_on:
      - elastic
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  app:
    container_name: csxp_app
    image: csxpi_app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod.app
    ports:
      - 8882:8880
    depends_on:
      - server
      - elastic
  mysql:
    image: "mysql:5.7"
    profiles:
      - "analytics"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_PASS}
      MYSQL_DATABASE: analytics
    command: --max_allowed_packet=128000000 #Bytes
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: csxp_analytics_db
  analytics:
    image: matomo:latest
    profiles:
      - "analytics"
    container_name: csxp_analytics
    restart: unless-stopped
    volumes:
      - ./analytics:/var/www/html
    environment:
      MATOMO_DATABASE_HOST: csxp_analytics_db
      MATOMO_DATABASE_USERNAME: root
      MATOMO_DATABASE_PASSWORD: ${MATOMO_PASS}
      MATOMO_DATABASE_DBNAME: analytics
    ports:
      - 8883:80
    links: [mysql]
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    profiles:
      - "elastic"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASS}
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # - ./elasticsearch:/var/lib/elasticsearch/data
      - ./elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped
    container_name: csx_elastic
  mongo:
    image: mongo:4
    volumes:
      - ./mongo:/data/db
    restart: unless-stopped
    container_name: csx_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

volumes:
  mongo-volume:
    external: false