version: "3.8"
services:
  server:
    container_name: csxp_server
    image: csxpi_server
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.server
    ports:
      - 8881:80
    environment:
      DISABLE_UPLOAD: 'false'
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
  app:
    container_name: csxp_app
    image: csxpi_app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod.app
    ports:
      - 8882:8880
    depends_on:
      # - mysql
      - server
      - elastic
      # - analytics
    # command: bash -c "node server.js"
  # mysql:
  #   image: "mysql:5.7"
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test
  #   command: --max_allowed_packet=128000000 #Bytes
  #   # ports:
  #   #     - "3316:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   container_name: csxp_analytics_db
  # analytics:
  #   image: matomo:latest
  #   container_name: csxp_analytics
  #   restart: unless-stopped
  #   volumes:
  #     - ./analytics:/var/www/html
  #   environment:
  #     MATOMO_DATABASE_HOST: csxp_analytics_db
  #     MATOMO_DATABASE_USERNAME: test
  #     MATOMO_DATABASE_PASSWORD: test
  #     MATOMO_DATABASE_DBNAME: analytics
  #   ports:
  #     - 8883:80
  #   links: [mysql]
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # - ./elasticsearch:/var/lib/elasticsearch/data
      - ./elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped
    container_name: csx_elastic
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    restart: unless-stopped
    container_name: csx_mongo

volumes:
  mongo-volume:
    external: false